version: '3.9'

services:
  mongodb:
    image: mongo:latest
    container_name: celeritas_mongodb
    ports:
      - "${MONGO_PORT:-27017}:27017"
#    volumes:
#      - ./data/mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}

  telegram_bot:
    build:
      context: .
      dockerfile: Dockerfile_telegram_bot
    container_name: celeritas_telegram_bot
    volumes:
      - ./data:/app/data
    network_mode: "host"
    command: python run_telegram_bot.py
    depends_on: 
      - mongodb
    environment:
      - TELEGRAM_BOT_TOKEN
      - SOLANA_RPC_URL
      - SOLANA_WS_URL
      - PLATFORM_FEE_PUBKEY
      - MONGODB_URL=mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@localhost:${MONGO_PORT:-27017}

#  pump_fun_sniper:
#    build:
#      context: .
#      dockerfile: Dockerfile_pump_fun_sniper
#    container_name: celeritas_pump_fun_sniper
#    network_mode: "host"
#    command: python run_pump_fun_sniper.py
#    volumes:
#      - ./data:/app/data
#    depends_on: 
#      - mongodb
#    environment:
#      - TELEGRAM_BOT_TOKEN
#      - SOLANA_RPC_URL
#      - SOLANA_WS_URL
#      - PLATFORM_FEE_PUBKEY
#       - MONGODB_URL=mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@localhost:${MONGO_PORT:-27017}

#volumes:
#  mongo_data: