version: '3.9'

services:
  mongodb:
    image: mongo:latest
    container_name: celeritas_mongodb
    ports:
      - "${MONGO_PORT:-27017}:27017"
    volumes:
      - ./data/mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    restart: unless-stopped

  telegram_bot:
    build:
      context: .
      dockerfile: Dockerfile_telegram_bot
      args:
        - WEBHOOK_URL=${WEBHOOK_URL}
    container_name: celeritas_telegram_bot
    volumes:
      - ./data:/app/data
    network_mode: "host"
    depends_on: 
      - mongodb
    environment:
      - TELEGRAM_BOT_TOKEN
      - SOLANA_RPC_URL
      - SOLANA_WS_URL
      - PLATFORM_FEE_PUBKEY
      - ADMIN_TELEGRAM_ACCOUNT_ID
      - MAX_REQUESTS_PER_SECOND
      - MONGODB_URL=mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@localhost:${MONGO_PORT:-27017}
      - WEBHOOK_URL
      - WEBHOOK_PORT
    restart: unless-stopped

  tx_listener:
    build:
      context: .
      dockerfile: Dockerfile_tx_listener
      args:
        - WEBHOOK_URL=${WEBHOOK_URL}
    container_name: celeritas_tx_listener
    volumes:
      - ./data:/app/data
    network_mode: "host"
    profiles: [full]
    depends_on: 
      - mongodb
    environment:
      - TELEGRAM_BOT_TOKEN
      - SOLANA_RPC_URL
      - SOLANA_WS_URL
      - PLATFORM_FEE_PUBKEY
      - ADMIN_TELEGRAM_ACCOUNT_ID
      - MAX_REQUESTS_PER_SECOND
      - MONGODB_URL=mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@localhost:${MONGO_PORT:-27017}
    restart: unless-stopped

  pump_fun_sniper:
    build:
      context: .
      dockerfile: Dockerfile_pump_fun_sniper
    container_name: celeritas_pump_fun_sniper
    network_mode: "host"
    profiles: [full, no_transaction_listener]
    volumes:
      - ./data:/app/data
    depends_on: 
      - mongodb
    environment:
      - TELEGRAM_BOT_TOKEN
      - SOLANA_RPC_URL
      - SOLANA_WS_URL
      - PLATFORM_FEE_PUBKEY
      - ADMIN_TELEGRAM_ACCOUNT_ID
      - MAX_REQUESTS_PER_SECOND
      - MONGODB_URL=mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@localhost:${MONGO_PORT:-27017}
    restart: unless-stopped